In [1]:
# Fassinou Bile Master 2 DIT avril 23

from src.utils import DataProcessor

In [6]:
data_file = 'data/raw/owid-covid-data.csv'

# Créez une instance de DataProcessor en passant le chemin vers votre fichier de données
data_processor = DataProcessor(data_file)

# Appelez les méthodes pour effectuer les tâches
data_processor.clean_data()
data_processor.reduce_data(['iso_code', 'total_cases', 'new_cases'])
data_processor.feature_engineering('total_cases_now', 'total_cases', 'new_cases')
data_processor.summarize_stats('statistiques_sommaires.csv')

In [5]:
data_processor.data

       iso_code  total_cases  new_cases  total_cases_now
0           AFG          5.0        5.0             10.0
1           AFG          5.0        0.0              5.0
2           AFG          5.0        0.0              5.0
3           AFG          5.0        0.0              5.0
4           AFG          5.0        0.0              5.0
...         ...          ...        ...              ...
166321      ZWE     236871.0      491.0         237362.0
166322      ZWE     237503.0      632.0         238135.0
166323      ZWE     237503.0        0.0         237503.0
166324      ZWE     238739.0     1236.0         239975.0
166325      ZWE     239019.0      280.0         239299.0

[166326 rows x 4 columns]